/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Edges, Float, useGLTF } from '@react-three/drei';
import { useFrame, useLoader } from '@react-three/fiber';
import { Depth, Fresnel, LayerMaterial } from 'lamina';
import { useControls } from 'leva';
import React, { useRef } from 'react';
import * as THREE from 'three';

import Checker from '../Images/checker.png';
import MoonAlpha from '../Images/Moon.png';
export function Moon(props) {
  const { nodes, materials } = useGLTF('/Moon.gltf');
  const [colorMap, alpha] = useLoader(THREE.TextureLoader, [Checker, MoonAlpha]);
  const meshRef = useRef();

  const ref = useRef();
  const { gradient } = useControls({ gradient: { value: 0.7, min: 0, max: 1 } });

  useFrame((state) => {
    const cos = Math.cos(state.clock.elapsedTime) * 1;
    const sin = Math.sin(state.clock.elapsedTime) * 1;
    ref.current.layers[0].origin.set(cos / 2, 0, 0);
    ref.current.layers[1].origin.set(cos, sin, cos);
    ref.current.layers[2].origin.set(sin, cos, sin);
    ref.current.layers[3].origin.set(cos, sin, cos);
  });

  return (
    <group {...props} dispose={null} scale={9}>
      <Float
        speed={1} // Animation speed, defaults to 1
        rotationIntensity={0} // XYZ rotation intensity, defaults to 1
        floatIntensity={1} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
        floatingRange={[-0.15, 0.15]} // Range of y-axis values the object will float within, defaults to [-0.1,0.1]
      >
        <mesh
          geometry={nodes.Moon.geometry}
          material={materials.Moon}
          ref={meshRef}
          position={[0, -0.6, 0]}
          rotation={[Math.PI * 0.5, -0.6, Math.PI]}
          scale={0.8}
        >
          {/* <meshStandardMaterial color={'red'} /> */}
          <LayerMaterial ref={ref} toneMapped={false}>
            <Depth
              colorA="#ff0080"
              colorB="black"
              alpha={1}
              mode="normal"
              near={1 * 3.5 * gradient}
              far={1 * 3.5}
              origin={[0, 0, 0]}
            />
            <Depth
              colorA="blue"
              colorB="#f7b955"
              alpha={1}
              mode="add"
              near={1 * 14 * gradient}
              far={1 * 14}
              origin={[0, 1, 1]}
            />
            <Depth
              colorA="green"
              colorB="#f7b955"
              alpha={1}
              mode="add"
              near={1 * 21 * gradient}
              far={1 * 21}
              origin={[0, 1, -1]}
            />
            <Depth
              colorA="white"
              colorB="red"
              alpha={1}
              mode="overlay"
              near={1 * 8 * gradient}
              far={1 * 8}
              origin={[1, -1, -1]}
            />
            <Fresnel mode="add" color="white" intensity={0.5} power={1.5} bias={0.05} />
          </LayerMaterial>
        </mesh>
      </Float>
      {/* <Effects/> */}
    </group>
  );
}

useGLTF.preload('/Moon.gltf');
