/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/ScrollTest3.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh
          name="cloth_parent_(Copy)"
          geometry={nodes['cloth_parent_(Copy)'].geometry}
          material={nodes['cloth_parent_(Copy)'].material}
          morphTargetDictionary={nodes['cloth_parent_(Copy)'].morphTargetDictionary}
          morphTargetInfluences={nodes['cloth_parent_(Copy)'].morphTargetInfluences}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/ScrollTest3.glb');
